### ISSUE TITLE
Base metrics for OLM v1

### ISSUE THREAD

**Issue by OchiengEd** [operator-framework/operator-controller#1058]
Gather baseline metrics for catalogd and operator-controller to be used as a reference point.

**Comment by yuriolisa** [comment]
@OchiengEd, what do you think about instrumenting the Operator Controller with the OpenTelemetry SDK? So, we could expose metrics, traces, and logs in a standard way.

**Comment by OchiengEd** [comment]
The goal of the metrics in this case is to detect drastic changes in compute resource utilization during development.  Therefore it should be able to be run from CI.

**Comment by OchiengEd** [comment]
[Attached](https://github.com/OchiengEd/olmv1-stats/blob/main/olmv1-metrics.pdf) is the baseline metrics report on the current state of compute resource utilization for `operator-controller` and `catalogd`.

Scripts and Jupyter Notebook used to generate the above report can be found in the [olmv1-stats](https://github.com/OchiengEd/olmv1-stats) repository.
