### ISSUE TITLE
Create OLM V1 release branch or repository

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-controller#111]
We need a single source of truth from which to cut each released version of OLM V1. This project could exist in a branch of the operator-lifecycle-manager repository, the operator-controller repository, or in a separate repository all on its own. 

Regardless of where it exists, it should contain, for each release version of OLM V1, a manifest of versions for each sub-component. This can then be referenced when an install script is run to install each sub-component at the version specified for that particular OLM V1 release.

Acceptance criteria:
- A single source of truth for OLM V1 release versions is created.
- The branch or repository that is created contains a manifest for each release version, each pointing to the appropriate versions of all sub-components to be installed.
- A `README.md` is creating explaining the purpose of the repository.

**Based on discussion**: We're leaning towards creating a new repository for this. Call it [github.com/operator-framework/olmv1-installer](github.com/operator-framework/olmv1-installer).

**Comment by awgreene** [comment]
Completed and available here: https://github.com/operator-framework/olmv1-installer
