### ISSUE TITLE
ClusterCatalog label policy enforcement + test - catalogd

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#1114]
Possibly as a validating webhook that runs after the mutating webhook enforce labeling policy.

Policy enforcement includes, but maybe is not limited to:
Each catalog name label is uniquely named.

**Comment by bentito** [comment]
This isn't needed. The mutating webhook #1113 takes care of always making the label name equal to the ClusterCatalog name. This validation was potentially to check if there were duplicates if we allowed users to select the value of the label, which we don’t do.
