### ISSUE TITLE
Docs: Overall architecture documentation

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#1124]
As part of our reference documentation, we need an OLMv1 architecture diagram

- [ ] Documentation explaining the architecture
- [ ] Architecture Diagram (CatD + O-C, watch directions, catd https endpoint)
- [ ] Reviewed and signed-off by @joelanford 

Would be nifty is the architecture diagram could provide links (mermaid might support this functionality)

Current documentation is posted up at https://operator-framework.github.io/operator-controller/
New docs should be placed in [docs/drafts](https://github.com/operator-framework/operator-controller/tree/main/docs/drafts)

**Comment by LalatenduMohanty** [comment]
@joelanford suggested that if the diagram can have links to respective code paths/components, it would be very useful.

**Comment by LalatenduMohanty** [comment]
Working on a google doc https://docs.google.com/document/d/1pYmV5vHNPLVlMTc8qqqsQcdnbKH98j6aICUL5SwYsP0/edit, this is work in progress. Once I have enough content I will create a PR
