### ISSUE TITLE
Docs: Catalogd API reference

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#1125]
Write Catalogd API reference documentation. Sync with @michaelryanpeter to see if there are any tools that can go from godoc to the API reference. Another option might to source the information from the CRD which is in openAPI format. There might already be tools to process that. (See what k8s does here: https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-api/)

- [ ] ClusterCatalog API reference documentation

Current documentation is posted up at https://operator-framework.github.io/operator-controller/
New docs should be placed in [docs/drafts](https://github.com/operator-framework/operator-controller/tree/main/docs/drafts)

> [!NOTE]
> This documentation should be written _after_ https://github.com/operator-framework/catalogd/issues/239

**Comment by michaelryanpeter** [comment]
Docs generation tooling for the downstream OpenShift client: https://github.com/openshift/oc/tree/master/tools/gendocs
