### ISSUE TITLE
Automate OLM V1 release

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-controller#113]
To help facilitate a simple and repeatable release process, tools should be created to automate it as much as possible. This automation should exist in whichever repository is chosen or created from #111. 

When invoked it should create a new manifest containing the chosen versions of each sub-component, then make that manifest available for use.

Acceptance criteria:
- Automation (i.e. github action) is created for OLM V1 releases.
- The automation populates a manifest with the chosen versions of each OLM V1 sub-component.
- The chosen automation finally publishes the release.

**Comment by awgreene** [comment]
After [a discussion](https://kubernetes.slack.com/archives/C0181L6JYQ2/p1680197298438769?thread_ts=1680181705.599479&cid=C0181L6JYQ2) on Slack, we've decided to treat each release of OLM V1 as an operator-controller release.

Marking this as obsolete and closing the issue.
