### ISSUE TITLE
Docs: Choosing what catalog ClusterExtensions come from

### ISSUE THREAD

**Issue by bentito** [operator-framework/operator-controller#1132]
Users need to understand setting the preferred ClusterCatalog name to get a ClusterExtension from.

They also need to understand setting priorities to break ties when package/bundle/version are available in multiple catalogs.
RFCS: 
* [Minimal Catalog Selection - Labels](https://docs.google.com/document/d/1v9iPRZHt1YXhwK9__7OITnEN430lryQzWaAaIpn---Y/edit?usp=drive_link)
* [Minimal Catalog Selection - Priority](https://docs.google.com/document/d/1jGAOvE0yf_U2lpyhy2U0KPLGOaG-8-ML0lve1mR-o1Q/edit?usp=drive_link)

**Comment by dhoover103** [comment]
Doc is ready for review - you can find it at https://docs.google.com/document/d/1wxmEbaDCWUqCSkeYnAP6uFTOGubvhUx6cT0gsihwE1g/edit?usp=sharing

**Comment by bentito** [comment]
So sorry @dhoover103 we somehow created #1154 for the docs for this epic. I didn't catch that this issue already existed. I see your gDoc here. Could you merge improvements/changes from that into the doc PR here: https://github.com/operator-framework/operator-controller/pull/1227 . Thanks so much!

**Comment by LalatenduMohanty** [comment]
This a duplicate of #1154
