### ISSUE TITLE
Add documentation for Minimal Catalog Selection

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#1154]
RFCs: 
[Minimal Catalog Selection - Labels](https://docs.google.com/document/d/1v9iPRZHt1YXhwK9__7OITnEN430lryQzWaAaIpn---Y/edit?usp=drive_link)
[Minimal Catalog Selection - Priority](https://docs.google.com/document/d/1jGAOvE0yf_U2lpyhy2U0KPLGOaG-8-ML0lve1mR-o1Q/edit?usp=drive_link)

**Comment by tmshort** [comment]
Related to #1132

**Comment by tmshort** [comment]
Related to #1132

**Comment by LalatenduMohanty** [comment]
https://github.com/operator-framework/operator-controller/pull/1227 is merged. So closing this issue.
