### ISSUE TITLE
Bump catalogd to get the latest API changes

### ISSUE THREAD

**Issue by ankitathomas** [operator-framework/operator-controller#1201]
https://github.com/operator-framework/catalogd/pull/379 is changing the catalogd APIs. So as soon as it lands we need to bump catalogd version then switch to using the `Serving` condition type instead of `Unpacked` for ClusterCatalog availability checks.

**Comment by tmshort** [comment]
This has a depdency on https://github.com/operator-framework/catalogd/pull/379

**Comment by ankitathomas** [comment]
Addressed by https://github.com/operator-framework/operator-controller/pull/1329
