### ISSUE TITLE
Docs: Downgrade a ClusterExtension

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#1229]
Write user documentation describing how to downgrade a package.

A placeholder for the document has already been created in [docs/drafts/Tasks/downgrading_an_extension.md](docs/drafts/Tasks/downgrading_an_extension.md).

For downgrades I think there are some specific overrides a user would need to put in place, namely:
 - Ignoring the catalog provided upgrade constraints
 - Disabling the CRD checks

**Comment by michaelryanpeter** [comment]
I think most of the content (besides disabling CRD checks) already exists here: https://github.com/operator-framework/operator-controller/blob/main/docs/drafts/upgrade-support.md#manually-verified-upgrades-and-downgrades

**Comment by michaelryanpeter** [comment]
@bentito ^

**Comment by bentito** [comment]
thanks @michaelryanpeter

**Comment by LalatenduMohanty** [comment]
Closing this as https://github.com/operator-framework/operator-controller/pull/1277 has merged
