### ISSUE TITLE
Docs: Single ClusterExtension ownership concept

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#1247]
#736 has become a documentation-only epic, so this issue tracks authoring that doc. From the description:

> For v1.0.0 it was decided that utilizing the underlying Helm management when concurrent reconciliations is set to a value of 1 is sufficient. While the underlying implementation details may change to prevent race conditions when scaling concurrent reconciliations > 1, the behavior that no two ClusterExtensions should be able to manage the same underlying objects needs to be documented.
>
> Documentation should be contributed to the [docs/drafts/ directory](https://github.com/operator-framework/operator-controller/tree/main/docs/drafts?rgh-link-date=2024-04-04T17%3A20%3A43Z)

**Comment by LalatenduMohanty** [comment]
https://github.com/operator-framework/operator-controller/pull/1258 is under reveiw

**Comment by everettraven** [comment]
#1258 merged
