### ISSUE TITLE
[CRD Upgrade Safety] Message output use the human readable value instead of exact bytes 

### ISSUE THREAD

**Issue by KeenonLee** [operator-framework/operator-controller#1248]
When upgrading a CRD, 
A new default value is added to a field that did not previously have a default value
The default value of a field is changed
An existing default value of a field is removed

This looks like it is behaving properly but the exact message output seems pretty unhelpful since it seems to be giving the exact bytes instead of a human readable value. 
we get an output similar to:
<pre>
message: 'validating upgrade for CRD "nginxolm75124s.cache.example.com" failed:
      CustomResourceDefinition nginxolm75124s.cache.example.com failed upgrade safety
      validation. "ChangeValidator" validation failed: version "v1alpha1", field "^.spec.field":
      new value added as default when previously no default value existed: &JSON{Raw:*[34
      100 101 102 97 117 108 116 45 115 116 114 105 110 103 45 106 105 116 108 105
      34],}'
</pre>

<pre>
message: 'validating upgrade for CRD "nginxolm75124s.cache.example.com" failed:
      CustomResourceDefinition nginxolm75124s.cache.example.com failed upgrade safety
      validation. "ChangeValidator" validation failed: version "v1alpha1", field "^.spec.defaultenum":
      default value has been changed from [34 118 97 108 117 101 49 34] to [34 118
      97 108 117 101 51 34]'
</pre>

<pre>
message: 'validating upgrade for CRD "nginxolm75124s.cache.example.com" failed:
      CustomResourceDefinition nginxolm75124s.cache.example.com failed upgrade safety
      validation. "ChangeValidator" validation failed: version "v1alpha1", field "^.spec.defaultint":
      default value has been removed when previously a default value existed: [57]'
</pre>

**Comment by KeenonLee** [comment]
Hi @everettraven , I create a issue to trace it, How can I remove the label [kind/documentation]

**Comment by everettraven** [comment]
> Hi @everettraven , I create a issue to trace it, How can I remove the label [kind/documentation]

Removed and added `kind/bug` instead - thanks for filing the issue @KeenonLee !
