### ISSUE TITLE
RFC for OLMv1 monorepo idea

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#1254]

**Comment by everettraven** [comment]
I was planning to write up more this week but haven't had a chance so far

**Comment by OchiengEd** [comment]
Sounds good. I can get started on it an reach out if I need clarification.

**Comment by bentito** [comment]
From today's o-f office hours Notes:

Monorepo for v1 discussion?
Combining catalogd and operator-controller into one binary (up & down stream)
We need an RFC and answer the following questions:
Do we want a single repo or multiple repos?
Do we want a single deployment for catalogd & operator-controller or separate?
Once we have direct bundle install we might want to consider having a “do not deploy catalogd” deployment option
Do we want a single binary for catalogd & operator-controller or separate?
Can we do this without it being a blocker for v1.0 GA downstream?

**Comment by LalatenduMohanty** [comment]
Lets have a meeting for an hour for writing the RFC together and go through these questions, specially is this something we want to block 1.0.0  release for this.

**Comment by LalatenduMohanty** [comment]
RFC: [link](https://docs.google.com/document/d/1mNzwtxhmZyk7fnkO_4AoCCnRR0qC98dOg5GZSJkI8qY/edit)

**Comment by LalatenduMohanty** [comment]
Thanks @OchiengEd for creating the epic and followup tasks https://github.com/operator-framework/operator-controller/issues/1335.
