### ISSUE TITLE
RFC: Review and update OperatorController condition types and status update logic

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#1256]
Similar to catalogd effort in https://github.com/operator-framework/catalogd/pull/379 and the catalogd RFC https://docs.google.com/document/d/1Kg8ovX8d25OqGa5utwcKbX3nN3obBl2KIYJHYz6IlKU/edit

**Comment by everettraven** [comment]
RFC here: https://docs.google.com/document/d/1DAUsVjeT1PJgUrbBdQjJh9eCOesOdlEhxKpVoV1_7m4/edit?usp=sharing

**Comment by everettraven** [comment]
RFC closed as approved and issues created for the resulting work items. Closing this issue.
