### ISSUE TITLE
[v1 API Review] Remove the `Unpacked` status condition

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#1294]
The `Unpacked` status condition will be replaced by the `Progressing` condition implemented as part of #1292. Once it is implemented, we need to remove the `Unpacked` condition.

For more information, see the [RFC](https://docs.google.com/document/d/1DAUsVjeT1PJgUrbBdQjJh9eCOesOdlEhxKpVoV1_7m4/edit?usp=sharing)

**Comment by LalatenduMohanty** [comment]
PR: https://github.com/operator-framework/operator-controller/pull/1309
