### ISSUE TITLE
Ensure rollouts are completed before starting a new upgrade.

### ISSUE THREAD

**Issue by thetechnick** [operator-framework/operator-controller#1296]
Interruptions during bundle reconciliation could lead to operator-controller not completing the current running rollout and instead pick up the next available release from the catalog.

Not rolling out a release completely, may lead to inconsistent results and unexpected behavior.

;tldr: Binary restarts and transient errors should not trigger re-resolve bundle images when a rollout is still in flight.

**Comment by joelanford** [comment]
Discussion in WG meeting:
- If the upgrade fails because of an ephemeral error, we should try to complete the rollout of the failed release.
- If the upgrade fails because of a "blocking" error, we should discard the failed release, re-resolve and proceed with an upgrade using the newly resolved bundle.

Need to be careful returning nil errors while we are in this retrying state (in either of the above cases).

**Comment by LalatenduMohanty** [comment]
@thetechnick The PR has merged now, so please test it and reopen the issue if you still see the issue.

**Comment by everettraven** [comment]
Reopening this issue as we identified the fix that was merged in #1349 builds on the Helm library `Get` call and that call is insufficient for making an appropriate decision as to what the latest successfully deployed release is. 

We identified in a sync call that we should instead:
- Add a `List` method to the helm-operator-plugins `ActionInterface` that allows us to use the Helm library `List` functionality. This allows filtering releases by specific criteria (like status == Deployed), and sorting
- Use the new `List` method in operator-controllers `InstalledBundleGetter` implementation to only return the most recent release that has status == Deployed
    - NOTE: Using `List` would make it such that OLM v1 won't upgrade from a "partial upgrade" _UNLESS_ there is another preferred upgrade path on a future resolution attempt.

**Comment by LalatenduMohanty** [comment]
Here is PR in [helm-operator-plugins](https://github.com/operator-framework/helm-operator-plugins)  repo to get more information about the state of release https://github.com/operator-framework/helm-operator-plugins/pull/397

**Comment by LalatenduMohanty** [comment]
Marking it done as https://github.com/operator-framework/operator-controller/pull/1379 has merged
