### ISSUE TITLE
Separate the tools and build output from bin folder

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-controller#135]
Currently the build binary output and tool binaries are both getting put into the `bin/` folder. This adds a lot of overhead to the docker build context and slows down the builds. 
Rukpak uses a separate tools folder with its own go.mod used to pull down the tools it needs. We should add something like this and make the required changes to the Makefile to support that. That will let us keep a separate binary folder for the build output.

**Comment by ankitathomas** [comment]
Solved with the switch to bingo as of https://github.com/operator-framework/operator-controller/pull/252
