### ISSUE TITLE
External API review submission

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-controller#1358]
We should submit both catalogd and operator-controller code for external review.

**Comment by LalatenduMohanty** [comment]
Here is the PR for external review https://github.com/openshift/api/pull/2067

**Comment by grokspawn** [comment]
- catalogd api updates: https://github.com/operator-framework/catalogd/pull/443
- operator-controller api updates: https://github.com/operator-framework/operator-controller/pull/1404
