### ISSUE TITLE
operator-controller side code implemention for "Optional field to mark a ClusterCatalog as Enabled/Disabled "

### ISSUE THREAD

**Issue by LalatenduMohanty** [operator-framework/operator-controller#1372]
operator-controller side code implemention for "Optional field to mark a ClusterCatalog as Enabled/Disabled " . For details refer the RFC [1]

[1] https://docs.google.com/document/d/1VmncLojrZFAEjRBIz0KwZlB_7K4ENTpCLPZfzHJRVDA/edit?pli=1#heading=h.x3tfh25grvnv

**Comment by bentito** [comment]
Draft PR for this work: https://github.com/operator-framework/operator-controller/pull/1359
