### ISSUE TITLE
CatalogSource CRD needed in installation steps

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-controller#145]
Without the CatalogSource CRD, the operator-controller cannot currently run. We should:
1. Have users install OLM v0 so we can use the catalog source pods.
2. Introduce code to have operator-controller gracefully degrade and log the issue instead of crash-looping.

The error in question: 
```
home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/source/source.go:132
1.6801246250976682e+09	ERROR	controller-runtime.source	if kind is a CRD, it should be installed before calling Start	{"kind": "CatalogSource.operators.coreos.com", "error": "no matches for kind \"CatalogSource\" in version \"operators.coreos.com/v1alpha1\""}
```

**Comment by ankitathomas** [comment]
https://github.com/operator-framework/operator-controller/pull/246 removes the CatalogSource CRD requirement
