### ISSUE TITLE
Update docs to use example which better demonstrates upgrades

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#1459]
Follow up to https://github.com/operator-framework/operator-controller/pull/1443:

- [ ] Need a better example for ["Upgrade an Extension" doc](https://github.com/operator-framework/operator-controller/blob/aaa0e0090ec0a04bbc990bbda0a4146852cf70bf/docs/tutorials/upgrade-extension.md): currently we use  argocd 0.5.0 -> 0.6.0 which fails CRD checks.
- [ ] We also need a better example for "Getting Started": we are [currently suggesting to upgrade](https://github.com/operator-framework/operator-controller/blob/main/docs/getting-started/olmv1_getting_started.md?plain=1#L79-L83) to 0.11.0 and it fails.

**Comment by trgeiger** [comment]
So there's a couple things of note here:

[As you can see here](https://github.com/operator-framework/operator-controller/blob/main/docs/concepts/upgrade-support.md#upgrades-within-the-major-version-zero) we don't support automatic upgrades between minor versions within major version zero. So even if the CRD Upgrade Safety check passes, we can't automatically upgrade between, for example, 0.5.0 and 0.6.0 anyway. There's not many patch versions to choose from in ArgoCD, but I did find that 0.2.0 will upgrade to 0.2.1. Any versions newer than 0.6.0 have webhooks and so aren't supported.

Would changing the example to use 0.2.0 and 0.2.1 be good enough? If we do that, we should add a reference to this major version 0 limitation on the tutorial page. Or do we want to find a new ClusterExtension example entirely that has workable non-zero major versions? If we go that route I'll need to derive all the RBAC and basically create an entirely new sample manifest.

**Comment by trgeiger** [comment]
Please see the draft linked PR for an example of changing to using 0.2.0 and 0.2.1.

As for the 2nd item in this issue, the use of 0.11.0 as the upgrade example, I'm not sure we can really use any of the newer versions of argocd without running afoul of either the CRD Upgrade Safety preflight check, the presence of webhooks, or the fact that we don't automatically upgrade between minor versions with a major version of 0. Is it okay to just stick to 0.2.0 and 0.2.1 of argocd in our example documentation or should we find another operator that would fulfill all these requirements as an example?

**Comment by trgeiger** [comment]
Those were basically my concerns as well--the time it would take to come up with an alternative and if that alternative would even stay stable in the future for us. I could see a benefit to maintaining some simple example operator in the future but that probably isn't really in the cards for fixing things up before v1 right now.

I'll move ahead with changing the docs to use 0.2.0/0.2.1 and we can move from there in the future.

**Comment by trgeiger** [comment]
I think we can close this now. #1469 addressed the first line item, and the second line item I think we agreed can be handled separately in #1480 when we handle duplicated content across different docs.

**Comment by m1kola** [comment]
Yes, closing this one. Thanks for handling this, Tayler.
