### ISSUE TITLE
Fix "Return list of packages that support `AllNamespaces` install mode and do not use webhooks" catalog query in the docs

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#1460]
Need to fix "Return list of packages that support `AllNamespaces` install mode and do not use webhooks" query [here](https://github.com/operator-framework/operator-controller/blob/aaa0e0090ec0a04bbc990bbda0a4146852cf70bf/docs/tutorials/explore-available-content.md?plain=1#L98-L100) and [here](https://github.com/operator-framework/operator-controller/blob/aaa0e0090ec0a04bbc990bbda0a4146852cf70bf/docs/howto/catalog-queries.md?plain=1#L24-L26).

Currently the query returns nothing.

**Comment by m1kola** [comment]
@grokspawn did a bit of investigation and here are the important bits:

> The issue appears to be that the catalog has shifted from bundle-level metadata stashed in `olm.bundle.object` to `olm.csv.metadata`.

> Here's a flawed replacement for jq when `olm.csv.metadata` is present in the catalog:
> ```
> jq -cs '.[]|select(.schema == "olm.bundle") | {"package":.package, "version": .properties[] | select(.type == "olm.package").value.version, "compatibleInstallMode": .properties[] | select(.type == "olm.csv.metadata").value | select((.installModes[] | select(.type == "AllNamespaces" and .supported == true))).labels[]}'
> ```
> Flawed because it seems to report each matching entry three times.

**Comment by bentito** [comment]
Fixed in https://github.com/operator-framework/operator-controller/pull/1464
