### ISSUE TITLE
Docs: example ClusterExtension is missing lease verbs

### ISSUE THREAD

**Issue by trgeiger** [operator-framework/operator-controller#1478]
[This section](https://operator-framework.github.io/operator-controller/howto/derive-service-account/#step-5-operator-permissions-declared-in-the-clusterserviceversion) of our docs on deriving the provided ServiceAccount permissions for a ClusterExtension shows that ArgoCD requires verbs for "lease" in "coordination.k8s.io." However, our example in config/examples is missing these permissions.

**Comment by rashmi43** [comment]
my fork was a mess, force rebased it to master and created a new PR
