### ISSUE TITLE
Add linter make target

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-controller#159]
We should add a `make lint` target and add it to the normal release/build automation for PRs to help us keep our code quality standards high.

Acceptance Criteria:
* Add `make lint` target or equivalent `golangci-lint` runner.
* Add the make target to the automation that runs during build.

**Comment by m1kola** [comment]
I think we can close this one. We already have `make lint`. Also we have ["sanity" job](https://github.com/operator-framework/operator-controller/blob/9c7291ddf6bbe55c7efd20e5e82f146d6cca9a80/.github/workflows/sanity.yaml) which runs it.
