### ISSUE TITLE
Honoring an optional `spec.channel` field in the `Operator` API.

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#163]
This issue should be closed when a demo recording is posted to the #olm-dev kubernetes slack channel that follows the below script:

Demo Script:

1. Install operator-controller from the main branch or its most recently tagged release using operator-controller's standard install script and manifest.
2. Create a `Catalog` object referencing `quay.io/operatorhubio/catalog:latest`
3. Show that the catalog status reflects that it was successfully unpacked.
4. Create an `Operator` object referencing package `strimzi-kafka-operator` with channel `strimzi-0.32.x`
5. Show that a `BundleDeployment` gets created and references the bundle image `quay.io/operatorhubio/strimzi-kafka-operator@sha256:0d4ac0ed10d815b30dca6521d3ceab5dfc150cddda22e9ca83e97462dbcfeff4`
6. Edit the `Operator` object and change the channel to `strimzi-0.33.x`
7. Show that the existing `BundleDeployment` is updated to reflect a new bundle image reference with `quay.io/operatorhubio/strimzi-kafka-operator@sha256:4d953d5fd719ea61a7009daaa7e37c948073132f231c2d2d1b07bf3d0d5d6e3b`
8. Edit the `Operator` object and remove the channel specification.
9. Show that the existing `BundleDeployment` is updated to reflect a new bundle image reference with the highest semver bundle defined in the package (as of 4/5/23, that version is 0.34.0):  `quay.io/operatorhubio/strimzi-kafka-operator@sha256:42a3dce711492fae22f2d919299a0594f152396f6c2fef65ffc47226ba9c786e`
10. Edit the `Operator` object and set the channel to `foobar`.
11. Show the the `Operator` object has its status updated to reflect that no version is available in the specified channel. Also show that the `BundleDeployment` is still present and remains at version 0.34.0.
12. Delete the `Operator` objects.

Related Issues:
- [x] #169 
- [x] #170

**Comment by tmshort** [comment]
Demo added to slack channel: https://kubernetes.slack.com/archives/C0181L6JYQ2/p1682347015950669

**Comment by pgodowski** [comment]
I know perhaps it's wrong place to ask the question, but let me ask anyway: What is the semantics in OLM v1 of the `channel` concept, in relation to OLM v0?

**Comment by joelanford** [comment]
@pgodowski - can you start a discussion topic for that question? In general the _concept_ is the same, but the mechanics are up for re-evaluation in OLMv1. I suspect we'll need to dive down into specific aspects of what you're trying to understand.

**Comment by joelanford** [comment]
I think we can call this one finished. In addition to the slack channel post, we demoed this at yesterday's WG meeting. Thanks to all involved!
