### ISSUE TITLE
(rough sketch dumps) Follow ups from catalogd-integration

### ISSUE THREAD

**Issue by anik120** [operator-framework/operator-controller#187]
* Set up e2e infrastructure for catalogd and operator controller: 
 - Devise action plan for what's best tested where, in what format (e2e vs unit). 
 - For any test that requires access to images hosted in an image registry, set up test suite to configure a local registry and use that registry for tests instead of reaching out to remote registry. 
 - For operator installation test, build a catalog with minimal set of operator/s, and use that instead of `quay.io/operatorhubio/catalog:latest`
 
* Review operator-controller e2e test suite: 
 - Structure tests to take advantage of ginkgo's DAG test path creation feature instead of laying all tests in a singe "It" block. 
 - (optionally)Eventually blocks can return error instead of taking in Gomega object in it's function signature. 

* Clean up "properties' values must be json objects" expectations in variable source implementation, more details [here](https://github.com/operator-framework/operator-controller/pull/182#discussion_r1180643813)   

* Move catalogd resources get/watch verbs for operator-controller closer to where they're needed (entitysource implementation). More details [here](https://github.com/operator-framework/operator-controller/pull/182#discussion_r1181697859)

**Comment by joelanford** [comment]
> For any test that requires access to images hosted in an image registry, set up test suite to configure a local registry and use that registry for tests instead of reaching out to remote registry.

For the vast majority of these tests, I would _much_ prefer to see this be "build image, kind load image, use imagePullPolicy IfNotPresent". This means there's no need for an actual image registry.

**Comment by joelanford** [comment]
> Eventually blocks can return error instead of taking in Gomega object in it's function signature.
AFAIK, they can return anything. And then you can assert on whatever is returned.

**Comment by anik120** [comment]
> > For any test that requires access to images hosted in an image registry, set up test suite to configure a local registry and use that registry for tests instead of reaching out to remote registry.
> 
> For the vast majority of these tests, I would _much_ prefer to see this be "build image, kind load image, use imagePullPolicy IfNotPresent". This means there's no need for an actual image registry.

That works too. But that also means we'll have to figure out how we can give access to the test clusters' context to the test suite, etc

**Comment by joelanford** [comment]
> That works too. But that also means we'll have to figure out how we can give access to the test clusters' context to the test suite, etc

We've got this setup working in the rukpak repo. It takes some effort, but once its setup it works really well.

**Comment by varshaprasad96** [comment]
> Another potential follow-on: https://github.com/operator-framework/operator-controller/pull/182/files#r1178493885

We probably may have to refactor this in a different way if [this](https://github.com/operator-framework/deppy/pull/95) gets in (if that's what we want to eventually do). cc: @perdasilva
