### ISSUE TITLE
[Epic] Refactor ginkgo unit tests to go test

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#189]
### Description
---
In discussion https://github.com/operator-framework/operator-controller/discussions/168, we've decided to avoid using ginkgo for unit testing. We need to move our current ginkgo unit tests to go test.

### Tasks
---
- [x] #190
- [x] #191
- [x] #192
- [x] #193
- [x] #194
- [x] #195
- [x] #196
- [x] #197

**Comment by tmshort** [comment]
With the latest set of commits, operator-controller is now ginkgo free!
