### ISSUE TITLE
Update controllers package tests

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#190]
## Description
---
Follow the testing guidelines set forth in #188 and refactor the [controllers package](https://github.com/operator-framework/operator-controller/tree/main/internal/controllers) unit tests. Be sure to fix all `**/*_test.go` files.

### Pre-Conditions
---
- [ ] #188 

### Acceptance Criteria
---
- [ ] All test files under the controllers package updated to conform to the guidelines in #188

**Comment by joelanford** [comment]
How do we plan to handle the `BeforeSuite`/`AfterSuite` setup that ginkgo provides? It handles things like setup/teardown of envtest, creation of a `rest.Config` object that tests can use to interact with the envtest apiserver, setup of a scheme, etc.

**Comment by m1kola** [comment]
Unit tests don't need `envtest`. Majority of our tests should be unit tests (think testing pyramid). Ones that require `envtest` are likely integration/e2e tests and we should probably keep them as Ginkgo tests.

**Comment by ncdc** [comment]
I'd like to eliminate Ginkgo entirely. I find it difficult to understand (BeforeEach, JustBeforeEach, BeforeSuite) and have an easier time reasoning about standard go tests (optionally table tests).

**Comment by m1kola** [comment]
@ncdc I'm not a big fan of Ginkgo too. Do you know any good examples of codebases which use standard go tests for e2e/integration tests? If yes - could you please share links? I can't think of any and in my head it looks even worse than with Ginkgo (setup, tear down).

**Comment by ncdc** [comment]
kcp
