### ISSUE TITLE
Update resolution/variablesources tests

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#192]
## Description
---
Follow the testing guidelines set forth in #188 and refactor the [resolution/variablesources](https://github.com/operator-framework/operator-controller/tree/main/internal/resolution/variablesources) unit tests.

### Pre-Conditions
---
- [ ] #188 

### Acceptance Criteria
---
- [ ] All test files strictly under the resolution package updated to conform to the guidelines in #188

**Comment by tmshort** [comment]
This has apparently been done.
