### ISSUE TITLE
Update util tests

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/operator-controller#197]
## Description
---
Follow the testing guidelines set forth in #188 and refactor the [variable source util package](https://github.com/operator-framework/operator-controller/tree/main/internal/resolution/variable_sources/util) unit tests.

### Pre-Conditions
---
- [ ] #188 

### Acceptance Criteria
---
- [ ] All test files strictly under the resolution package updated to conform to the guidelines in #188

**Comment by pradeepnnv** [comment]
I would like to contribute to this issue. Please assign this issue to me.
