### ISSUE TITLE
Removing or re-defining the meaning of the existing Ready condition.

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#201]
The installed condition proposed in #199 basically replaces the existing "Ready" condition. This ticket tracks the need to remove the existing "Ready" condition.

**Comment by joelanford** [comment]
Related: https://github.com/operator-framework/operator-controller/issues/126

**Comment by tmshort** [comment]
At this point is this a _removal_? Considering #199 and #202?

**Comment by joelanford** [comment]
For now removal seems reasonable. The alternative (if we want `Ready` to be a rollup of other status) is `Ready` == `Installed=True` + `Resolved=True` + `installedSource == resolvedSource`.

**Comment by joelanford** [comment]
Agreed. I think removal of `Ready` is fine if we have `Installed` and `Resolved`. As another follow-on, it would also be nice to have `Progressing`, somewhat as described in #126 (which would conceptually be "trying to get to `installedSource == resolvedSource`" or "i give up, my inputs need to change")

**Comment by tmshort** [comment]
I might be able to get #126 in, maybe? But the delete work is done.
