### ISSUE TITLE
'go run' uses GOOS=linux for local tools, even on non-linux platforms

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-controller#220]
https://github.com/operator-framework/operator-controller/blob/4ea83e6fbe666af5023d4e43f34110ac2cd27e24/Makefile#L115
makes GOOS 'sticky' for follow-on operations, and since it is the first dependency for the 'run' target, it /might/ be run first and carry that value over to other targets.

**Comment by joelanford** [comment]
Nah, that won't work. It's the `build` step that actually needs `GOOS=linux`, but only when `build` is invoked on behalf of `docker-build`. When `build` in invoked directly, it should use the host default GOOS.

**Comment by joelanford** [comment]
Here's what rukpak does: https://github.com/operator-framework/rukpak/blob/444cc33c70ec115517b74a12e1055650329baf6e/Makefile#L182-L183

Separate target for linux binaries.
