### ISSUE TITLE
Add upgrade policy

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#232]
**Background**
OLM V0 had a concept of an approver, to allow installs to occur.  This could be used indirectly as policy. OLM V1 no longer has an approver, and subsequently has no policies that can be applied to upgrades.

**Story**
- As an OLM V1 user, I would like to define operator upgrade policies for OLM V1 to follow.
- I want to restrict when the operator may be upgraded/installed.
- I want to restrict how the operator may be installed with other operators.
- I want to (further) restrict versions that may be upgraded to.

**Demo Script:**
1. Install OLM v1.
2. For each policy type:
3. Create an Operator CR for operator Foo at version spec.Version.
4. Update the Operator CR with the specified policy, and a new spec.Version that would cause an upgrade to occur.
6. Wait for the operator status to indicate policy violation.
7. Remove policy, or change the environment such that the policy is valid.
8. Check that the upgrade proceeds as expected.
9. Continue to next policy

**Implementations to Consider**
- Policy configured within the Operator CR vs referenced as a separate policy CR
- Policy using pre-defined fields, or generic (e.g. OPA)

**Policies to Consider**
- Time-based: time-of-day, day-of-week, day-of-month, etc.
- Skip versions: whether to skip versions, or to go iterate through every version.
- Serialization: whether to allow for parallel or serialized installs, possibly specifying other operators.
- Version policies: skip 0-z-stream, skip 0-y-stream.
- Enabled: upgrades enabled or disabled.
- ...others...?

**Follow Ups:**
- [ ] Update the demo script to reference an actual operator and version.
- [ ] Add implementable issues representing these policies.

**Comment by joelanford** [comment]
I feel like some of the ideas here may be conflating (for better or worse) a few distinct concepts:
1. constraints on what should be candidates to be upgraded to
2. _when_ to upgrade
3. _how_ to upgrade

For example, how would an upgrade policy that specifies "z-stream only" interplay with `operator.spec.version`? That seems like a confusing API.

Before we progress to implementation, would it make sense to hash out some of these details in a discussion?

**Comment by tmshort** [comment]
Yes, that's why I was non-specific. Policy is definitely a blanket term, and can cover how and when, along with other constraints. Specific issues would be created from this issue.

Whether or not all these are selected/implemented at this time, or another, is TBD.

What I was thinking for those items I listed:

Time-based: should be obvious.

Skip versions: If there are multiple upgrade edges: `1.1` -> `1.2` -> `1.3` and `1.1` -> `1.3`. One policy might be to take the longer path, another might be to take the quicker path. Not sure if it makes sense to do this, but some users might be paranoid about skipping versions.

Serialization: Whether to allow multiple operators to upgrade at the same time, or to disallow operators upgrading at the same time. For instance, a user may not want to have multiple operators updating at the same time, or may want o avoid having operator `foo` and operator `bar` update at the same time. This could possibly occur when a large catalog is updated.

Version policies: not sure if this could be specified via `.spec.version`, but some people don't like installing `x.x.0` versions. So, if an upgrade were available `1.1.1` -> `1.2.0`, then it might be blocked until an upgrade to `1.2.1` is available. At least that was the idea. Certainly, if `.spec.version` ranges could handle this, then this wouldn't be necessary. Regardless, I'd consider this low priority.

Enabled: simple enable/disable. Might be an easy way to disable all upgrades for any reason (e.g. an upgrade moratorium).

Cluster Load/health: don't update when a cluster is heavily loaded and/or unhealthy. Not sure how to measure this, might be if there are unhealthy/overloaded nodes.

**Comment by tmshort** [comment]
@joelanford: Ignoring version-related policies for now (which are _how_ policies as you point out), we can focus on _when_ policies:

* Time-based
* Enabled/Disabled
* Cluster Load/Health
* Serialization

These can each be done in turn, based on priority/difficulty.

A new `Condition` would need to be added, indicating policy enforcement/violation.

**Comment by joelanford** [comment]
Sounds good! One note about serialization policy is that it could cause problems related to dependency management (e.g. if two operators have to upgrade at the same time to satisfy dependencies).

**Comment by tmshort** [comment]
Yup, I thought about that (serialization causing issues with two operators/dependency management). We don't quite support that level of dependency management yet, however.

**Comment by ecordell** [comment]
I haven't been able to keep up with all of the work here, so I apologize for my lack of context. If it's helpful, approval was proposed to be based on the existing CertificateSigningRequest flow as part of RukPak. See: https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/#approval-rejection-api-client and https://hackmd.io/nS8lS71uSmCTaPGfbWII_g?view#Instance-API

**Comment by tmshort** [comment]
No intent to do this
