### ISSUE TITLE
Solver: Introduce constraints for "upgrade edges"

### ISSUE THREAD

**Issue by jmprusi** [operator-framework/operator-controller#267]
For an operator upgrade to be valid, the new operator version should comply with a set of constraints:

- Channel: The new operator version should be part of the same channel 
- Replaces: The currently installed operator version should be included in the "replace" field of the new desired operator version (see skips)
- Skips: Skips define from what version it is possible to jump to without upgrading one version at a time. This should be considered and not only the "replaces" field.  

related to https://github.com/operator-framework/operator-controller/issues/231

**Comment by joelanford** [comment]
Related: https://github.com/operator-framework/operator-controller/pull/274#discussion_r1240576998
