### ISSUE TITLE
Update catalog content retrieval method

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#293]
Upon completion of https://github.com/operator-framework/catalogd/milestone/4 catalogd will have a new method for serving catalog content via a HTTP server as opposed to Kubernetes CustomResources. Once the milestone is complete and a release of catalogd containing the changes has been cut, this method for retrieving catalog content for resolution needs to be updated.

**Comment by joelanford** [comment]
This is currently planned in catalogd [v0.6.0](https://github.com/operator-framework/catalogd/milestone/5). See https://github.com/operator-framework/catalogd/issues/139
