### ISSUE TITLE
`entity for package "project-quay" not found in solution` when trying to upgrade to the next version using replaces

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#321]
I'm getting `entity for package "project-quay" not found in solution` when trying to upgrade to the next version. 

`project-quay` uses `replaces` to speficy upgrade edges and support for this was added #275. I see that PR has an [e2e test confirming an upgrade](https://github.com/operator-framework/operator-controller/blob/fa84c733ade0f71f33085a978ae0163f570d48b7/test/e2e/install_test.go#L171-L213) so it might be that I'm missing something.

## Steps to reproduce

1. Run the operators from master:
  ```bash
  make run
  ```
1. Create a catalog:
  ```bash
  kubectl apply -f config/samples/catalogd_operatorcatalog.yaml
  ```
1. Create an operator
  ```bash
  kubectl apply -f - <<EOF
  apiVersion: operators.operatorframework.io/v1alpha1
  kind: Operator
  metadata:
    labels:
      app.kubernetes.io/name: operator
      app.kubernetes.io/instance: operator-sample
      app.kubernetes.io/part-of: operator-controller
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/created-by: operator-controller
    name: operator-sample
  spec:
    packageName: project-quay
    channel: stable-3.8
    version: 3.8.1
  EOF
  ```
1. Wait for the operator to be installed:
  ```bash
  kubectl wait operators operator-sample --for condition=Installed
  ```
1. Edit operator to have a next valid version (in this specific example - 3.8.2 replaces 3.8.1):
  ```bash
  kubectl patch operator operator-sample --type json -p '[{"op": "replace", "path": "/spec/version", "value": "3.8.2"}]'
  ```
1. Observe conditions:
  ```bash
  kubectl get operator operator-sample -o json | jq ".status"
  ```
  Output:
  
  ```json
  {
    "conditions": [
      {
        "lastTransitionTime": "2023-08-04T14:24:02Z",
        "message": "installation has not been attempted as resolution failed",
        "observedGeneration": 13,
        "reason": "InstallationStatusUnknown",
        "status": "Unknown",
        "type": "Installed"
      },
      {
        "lastTransitionTime": "2023-08-04T14:24:02Z",
        "message": "entity for package \"project-quay\" not found in solution",
        "observedGeneration": 13,
        "reason": "ResolutionFailed",
        "status": "False",
        "type": "Resolved"
      }
    ]
  }
  ```

## Expected results

Operator is correctly resolved and installed

**Comment by m1kola** [comment]
@joelanford v0.3.0 was cut before #275. So I think we missed something in #275, but I can't figure out what is the difference between my example and the E2E test which works.

I'll come back to it on Monday.

**Comment by m1kola** [comment]
From @jmprusi:

> I've seen issues with the version being written as  "v0.0.1"  vs "0.0.1" (that missing v)

We might need to add toleration for versions with `v`.

**Comment by joelanford** [comment]
I didn't see any `project-quay` bundles in the operatorhub catalog that use a `v` prefix in their `olm.package` property, so perhaps something else is going on?

**Comment by m1kola** [comment]
This turned out to be unrelated to `v` prefix. Our test catalog currently looks like this:

https://github.com/operator-framework/operator-controller/blob/dea70ebd327ad77da215d8981270de3df9bf1b32/testdata/catalogs/test-catalog/catalog.yaml#L6-L14

It looks like replaces in the test are in format `$packageName.$version` when in reality they are `$bundleName.$version`.

Most likely this means that controller also builds the problem incorrectly (using package name).
