### ISSUE TITLE
Create a package for scheme setup

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#322]
We already have multiple places where we setup scheme:
* https://github.com/operator-framework/operator-controller/blob/fa84c733ade0f71f33085a978ae0163f570d48b7/cmd/manager/main.go#L49-L53
* https://github.com/operator-framework/operator-controller/blob/fa84c733ade0f71f33085a978ae0163f570d48b7/cmd/resolutioncli/main.go#L62-L65
* https://github.com/operator-framework/operator-controller/blob/fa84c733ade0f71f33085a978ae0163f570d48b7/internal/controllers/suite_test.go#L70-L74
* Various tests

And more will be introduced (e.g #286 adds a new one, see `test/operator-framework-e2e/operator_framework_test.go`).

To avoid having this repeated setup and inconsistent schemas we should consider creating a scheme package in the project which will be setting up a scheme. In rest of the places we will just be able to import already constructed scheme.

Example:

* `kubectl` scheme - https://github.com/kubernetes/kubectl/blob/197123726db24c61aa0f78d1f0ba6e91a2ec2f35/pkg/scheme/install.go

**Comment by grokspawn** [comment]
solved by #770
