### ISSUE TITLE
Make catalogd's CatalogMetadata APIs available for operator-controller

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#334]
While we wait for https://github.com/operator-framework/catalogd/issues/139, I propose that we start using catalogd's `CatalogMetadata` API instead of its `BundleMetadata` and `Package` APIs.

The `CatalogMetadata` API contains (almost) all of the FBC that the eventual catalogd file server will, so it is a good step forward, and is something that folks implementing some of the existing RFCs can use _right now_. This will ease an eventual migration to the catalogd file server.

Catalogd `main` branch currently has `CatalogMetadata` APIs enabled. We just need to ask catalogd maintainers to cut a release and bump our dependency on it.

**Comment by m1kola** [comment]
Sounds good! I think this also solves this todo:

https://github.com/operator-framework/operator-controller/blob/fd7cfb57680c3949d7317a4ad4c33dc7a42f09d5/cmd/resolutioncli/entity_source.go#L120-L125

But instead of converting declcfg into CRDs as initially suggested in TODO we operate on declcfg everywhere.

**Comment by m1kola** [comment]
Sorry, I misunderstood it at first. This ticket only aims at making `CatalogMetadata` available to operator-controller which was already done in https://github.com/operator-framework/operator-controller/pull/339 / https://github.com/operator-framework/operator-controller/pull/336.

To solve the todo mentioned above I created #342.

I think we can close this issue.
