### ISSUE TITLE
Version Ranges: Introduce Masterminds/semver

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#346]
### Summary
The **Masterminds/semver** will be used to parse **.spec.version** field of the Operator CR.The regular expression contained in the CRD that clients use to validate input before sending to the server must be updated to support version ranges. Due to the complexity and imprecision of the hyphen (-) operator, it will not be included.

* Update the validator for **.spec.version** to use **Masterminds/semver**.
* Update the variable source code to use **Masterminds/semver** APIs
* Update other code locations as necessary
* Use the alias `mmsemver` (may change in PR) to refer to **Masterminds/sever** to distinguish it from **blang/semver**. 
* Validate existing unit & e2e tests continue to work.
* Add unit tests to validate ranges, both positive and negative; this should be done _without_ a client (i.e. ginkgo). If necessary, remove the regex in the CRD definition to allow ranges to be used.

### Reference
[RFC: OLMv1 Version Ranges](https://docs.google.com/document/d/1Cf4vw6kdadNp3bHFxh5AMcq1xq0vsEUgC-JNEaVtU6g/edit?usp=sharing)

Update the Operator CR to support version ranges. There are no direct API changes.

### Related GitHub Issues

#345 

### Dependencies

https://github.com/operator-framework/operator-controller/issues/344

### Updates and Amendments

None.

**Comment by tmshort** [comment]
> * update

sion

**Comment by tmshort** [comment]
Fixed by #374 (apparently, you can't do `Fixes num and num`, and have GH detect that.

**Comment by joelanford** [comment]
> apparently, you can't do Fixes num and num, and have GH detect that

Yeah separate lines should do it though

```md
Fixes #345
Fixes #346
```
