### ISSUE TITLE
`make operator-developer-e2e` fails with podman

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#349]
`make operator-developer-e2e` builds and pushes images into local registry. Unfortunately it fails with `podman` when it is being used as a replacement for `docker`.

```
pinging container registry localhost:5001: Get "https://localhost:5001/v2/": http: server gave HTTP response to HTTPS client
```

This can be bypassed by setting `--tls-verify` to `false` in `podman push`. However, It looks like docker CLI doens't have this option.

**Comment by m1kola** [comment]
I believe a workaround for this is the following:

1. ```bash
    podman machine ssh
    sudo vi /etc/containers/registries.conf
    ```

1. Adding the following:
    ```bash
    [[registry]]
    location = "localhost"
    insecure = true
    ````

But this is not ideal since this has to be added after each podman machine recreation.

**Comment by tmshort** [comment]
But also only if you know you are using podman.
