### ISSUE TITLE
Update docs to show users to use `CatalogMetadata` API instead of `Packages` and `Bundles`

### ISSUE THREAD

**Issue by anik120** [operator-framework/operator-controller#371]
#342 should be followed up with a docs change

**Comment by joelanford** [comment]
I updated docs in the catalogd repo as part of https://github.com/operator-framework/catalogd/pull/149, so that may be the best place to reference what updates need to be made here.

**Comment by ankitathomas** [comment]
Done as of https://github.com/operator-framework/operator-controller/pull/694
