### ISSUE TITLE
[Epic] Initial upgrade support

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#377]
### Design docs

- [Brief: Initial upgrade support](https://docs.google.com/document/d/1KIhV8oqr22Bp8lf370Aej2n-3uW_xGcTptONHHPRVYA/edit#heading=h.btd8kkom5km4)
- [RFC: Initial upgrade support](https://docs.google.com/document/d/1dfiNr0kvP1nfS0f9xaGiLyfrJ_KcD38clYs4LYBKllk/edit)

### Precursor and related items
- #231 
- #267
- #275

### Task List
- #268 
- #395
- #396
- #397
- #398
- #449
- #470

**Comment by m1kola** [comment]
Added #449 since I realised that we do not cover `.spec.upgradeConstraintPolicy` in any other issue.

**Comment by m1kola** [comment]
Added #470 for documentation.
