### ISSUE TITLE
[Epic] Support version ranges

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#379]
### Design Docs

- [Brief: Support version ranges](https://docs.google.com/document/d/1iO067Ji4qE7d59nhkf5tF2tHpMaJyuEDfHn3mOWNdsc/edit#heading=h.btd8kkom5km4)
- [RFC: Support version ranges](https://docs.google.com/document/d/1Cf4vw6kdadNp3bHFxh5AMcq1xq0vsEUgC-JNEaVtU6g/edit?usp=sharing)

### Task List

- #356 
- ~#359~ 
- #344 
- #345 
- #346
- #374
- #407

**Comment by tmshort** [comment]
@joelanford, I believe this is done?

**Comment by joelanford** [comment]
@tmshort Shall we schedule a demo as a final task before closing this out?

**Comment by joelanford** [comment]
Demo here: https://www.youtube.com/watch?v=dyQZwc-87ws&t=781s

Thanks @tmshort!

**Comment by joelanford** [comment]
It sounds like there was some discussion of an action item to make sure docs are updated to reflect new version range support. I've added https://github.com/operator-framework/operator-controller/issues/407 and included it in this issue's task list.
