### ISSUE TITLE
Add semver upgrade edge generation support

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#398]
**Please read [RFC](https://docs.google.com/document/d/1dfiNr0kvP1nfS0f9xaGiLyfrJ_KcD38clYs4LYBKllk/edit) for better formatting and full scope.** The excerpt below is just to indicate the scope covered by this specific issue.

Need to implement semver upgrade edge generation function as discussed in the [RFC](https://docs.google.com/document/d/1dfiNr0kvP1nfS0f9xaGiLyfrJ_KcD38clYs4LYBKllk/edit#heading=h.zfkgmgda4f9w).

> ### Semver
> Semver based implementation is expected to:
> * Satisfy the interface discussed above
> * Return a list of successor bundles based on semver. The list will not include bundle versions outside the major version of the installed bundle. (In [semver](https://semver.org/#if-even-the-tiniest-backward-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly) a new major version is intended to indicate breaking changes, and we don’t want to default to that behavior. Future iterations may include knobs to extend this behavior.)
> * This mode will not allow downgrading.

As part of this issue we also need to make sure that `ForceSemverUpgradeConstraints` feature gate is respected:

> The solver needs to be able to switch between upgrade constraint semantics based on rules defined above (see Fig 1).

**Comment by grokspawn** [comment]
blocked by #347
