### ISSUE TITLE
Improve resolution efficiency

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#418]
It was brought up in https://github.com/operator-framework/operator-controller/pull/411#discussion_r1328441541 that multiple calls are made during resolution that results in bundle information being retrieved and processed multiple times.

We should see if we can optimize this by answering the following questions and making improvements as identified by the answers:
- Why does resolution make multiple calls to fetch bundle information?
- Can it just make one, and hold on to the data it needs?

**Comment by everettraven** [comment]
>Re: If-Modified-Since: it looks like https://github.com/operator-framework/operator-controller/pull/411 moving into the direction of not making a request at all and checking whether cache was made for a specific catalog image.

Instead of using the `If-Modified-Since` header, we are checking the resolved source of the `Catalog` and using that to determine if we need to refresh the cache. If the `Catalog` has not yet been cached _or_ we need to refresh the cache, we send a request for the catalog contents

**Comment by stevekuznetsov** [comment]
Something I've encountered in the `operator-lifecycle-manager` codebase that I think applies here as well - we need to ensure that the input to resolution is static. Today in the v0 codebase the resolver reads cluster state (via listers) and catalog state (via the cache) quite a large number of times during one resolution.

The resolver does not control who mutates cluster state, and when - if any object on the cluster changes while the resolver is running, or if a new catalog is loaded, _etc_, subsequent calls to fetch data during a resolution run will cause an incoherent view of the world and likely always end up with a failure to satisfy constraints or similar nonsense.

The `operator-controller` _must_ snapshot the world once and pass that data - statically - to the resolver. It's still possible that if e.g. two listers are used in tandem to snapshot the world, they will be out-of-sync with each other, but the general pattern for controllers is to re-queue objects when the input set changes. Therefore, a well-behaved controller tolerates temporary lister desync issues by eventually converging to the correct end state. It's important not to treat resolution errors as terminal logically - if the set of catalogs, `Operator`s, or `BundleDeployment`s changes, the outcome of resolution will, too.

**Comment by m1kola** [comment]
I think this will be resolved by #501

**Comment by m1kola** [comment]
I decided to split this out of #501 and created #508.

I will either need 4 parts of variable source refactoring to get merged or something similar to #508 so I can progress with #449
