### ISSUE TITLE
Bug: Non-latest version installed in packages with multiple channels

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#419]
What I did:
1. Install the operatorhubio `Catalog`
2. Create an `Operator` with just `spec.packageName: grafana-operator`

What happened:
- Grafana-operator v3.10.3 was resolved/installed

What I expected to happen:
- Grafana-operator v5.4.1 should have been resolved/installed

What I think is happening:
- We are sorting by channel priority and lexicographical name before sorting for version. Therefore bundles present in higher priority channels or in equal priority channels with lexicographically lower names are preferred.

What I think the fix is:
- Stop using channel for anything other than set membership checks. Specifically, remove [these lines](https://github.com/operator-framework/operator-controller/blob/4b9cfd94862dc486c02cf4482dff97f8429d007f/internal/resolution/util/sort/sort.go#L25-L29) (and related code/tests). It is not (yet at least) in the OLMv1 design for there to be channel priorities or for there to be any sorting related to channels. It is thus far meant to be purely a set membership attribute used to filter bundles via `spec.channel`.

**Comment by m1kola** [comment]
It looks like we are going to address this in #413, but to update tests as per [this](https://github.com/operator-framework/operator-controller/pull/413#issuecomment-1726886864) comment:

> It looks like this may actually resolve the issue from #419 as well. In this PR (or maybe a follow-up is okay), can we update the controller unit test and the e2e test to add a new `alpha` channel for the prometheus package that contains a non-latest version, and then update the relevant assertions to make sure that 0.65.1 is still the resolved bundle?
>
> See:
> - https://github.com/operator-framework/operator-controller/pull/420/files#diff-b97ef0be75ddfb0d44613fbe3583548b7e4e75ca45faf8d1cbf25e7600e3ed8a
> - https://github.com/operator-framework/operator-controller/pull/420/files#diff-a776550a4d41e3a27063ccc4c50e5cd7e0d90c5dc234cd96217b345a1e52ac54
> - https://github.com/operator-framework/operator-controller/pull/420/files#diff-041c5c4339769a620410df332c23ce9b0aa3e4824b26aadda8c5a5c6003e57cf

**Comment by m1kola** [comment]
I believe this was fixed in #413 + added coverage in #420. Closing.
