### ISSUE TITLE
Reduce number of variable sources involved in resolution process

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#437]
Today we have variable sources which create other variable sources which create variables. While this gives us very short and simple units - it makes harder to follow and creates a lot of boilerplate (e.g. need for support of nested variable soruces).

For example `OperatorVariableSource` creates `RequiredPackageVariableSource` which creates `RequiredPackageVariable`:

https://github.com/operator-framework/operator-controller/blob/6808a5020e579da6a5da0083bc066b1c1a63702d/internal/resolution/variablesources/operator.go#L42-L47

https://github.com/operator-framework/operator-controller/blob/6808a5020e579da6a5da0083bc066b1c1a63702d/internal/resolution/variablesources/required_package.go#L88-L90

`BundleDeploymentVariableSource` creates `InstalledPackageVariableSource` which creates `InstalledPackageVariable`:
https://github.com/operator-framework/operator-controller/blob/6808a5020e579da6a5da0083bc066b1c1a63702d/internal/resolution/variablesources/bundle_deployment.go#L47

https://github.com/operator-framework/operator-controller/blob/6808a5020e579da6a5da0083bc066b1c1a63702d/internal/resolution/variablesources/installed_package.go#L53-L55

**Comment by m1kola** [comment]
We can start by reducing number of variable sources so that variable sources don't create other variable sources.

We might still have to preserve custom variable types such as `InstalledPackageVariable` and `RequiredPackageVariable` since we use custom variable types to store references to bundles which are later used in other variable sources:

https://github.com/operator-framework/operator-controller/blob/6808a5020e579da6a5da0083bc066b1c1a63702d/internal/resolution/variablesources/bundles_and_dependencies.go#L46-L51

But this might be at some point resolved too. Soon we are going to be looking into potential next iterations for deppy and one of the ideas which was mentioned is adding "kind" and attributes to variables. This might be a good use case for it. But this still need to be fleshed out.

**Comment by perdasilva** [comment]
I think the general idea is to move to a monolith variable source that handles everything. The idea of introducing something like group/version/kind to Variables could help obviate the need to make your own implementations of the variable interface

**Comment by m1kola** [comment]
I updated this issue to focus on reducing number of varaible sources and created a separate issue for reducing number of variable types: #494
