### ISSUE TITLE
The generated Inputs leak over time from the catalog source adapter

### ISSUE THREAD

**Issue by timflannagan** [operator-framework/operator-controller#45]
The recent set of changes have introduced a new component that's solely responsible for aggregating catalog source catalog content, where each olm.bundle is modeled as a deppy Input resource. For the most part, this seems like it's a step in the right direction, but the current implementation leads to some false positives during e2e testing. When the original source for the generated Input is deleted (e.g. a specific catalog source resource), the Input is stranded, which leads to test pollution over time.

Unfortunately, the CatalogSource API is namespace-scoped, and therefore we can't place an owner reference on the underlying Input resource that was generated as the Input API is cluster-scoped, and garbage collection cannot occur in that edge case.

**Comment by exdx** [comment]
This is a rough edge of creating the Inputs on-cluster, for sure. I'd like to avoid manual garbage collection as part of the deppy controller if possible. 

Two possibilities:
* Add a `Source` CRD that wraps a catalog source -- any Inputs generated are ownerref'd by the Source. It does implicitly elevate catalog sources from Namespace -> Cluster scoped, but I think it's a nice abstraction.
* Don’t create an Input for every bundle on-cluster. We could have some server that’s responsible for storing Inputs and feeding them to resolution on demand, and it can keep it's internal cache of Inputs consistent with what's on cluster

**Comment by timflannagan** [comment]
Closing as this implementation is no longer relevant.
