### ISSUE TITLE
Docs about catalogd are outdated

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#451]
See https://github.com/operator-framework/operator-controller/blob/205a48778e07f96819381269cb652536c6f895e6/docs/Tasks/explore-available-packages.md

That doc talks about APIs that are no longer present in the version of catalogd used by operator-controller.

**Comment by makon57** [comment]
Looks like the doc has been updated by @michaelryanpeter :
- https://github.com/operator-framework/operator-controller/blob/main/docs/Tasks/explore-available-packages.md
