### ISSUE TITLE
write an RFC for graph deprecation controller impacts

### ISSUE THREAD

**Issue by grokspawn** [operator-framework/operator-controller#452]
Write an RFC based on [brief](https://docs.google.com/document/d/17SaY8i8oaNlqx-akyj0CZQllnEUrqoXGIPIFk_rDcsY/edit) to develop a shared design intent on graph delegation 

Acceptance Criteria
- satisfies functional requirements of brief
- documents updates to Operator CR
- documents impacts to legacy successors listing with deprecated bundles
- identifies documentation impacts
- is reviewed and approved

blocked by https://github.com/operator-framework/operator-registry/issues/1146

**Comment by everettraven** [comment]
RFC: https://docs.google.com/document/d/1CYGANKILfzfOoWtHvyg4luF7i-cC1NRa7_1N9xTLatw/edit?usp=sharing

**Comment by everettraven** [comment]
RFC closed and approved
