### ISSUE TITLE
Possibility of an upgrade from one package to another

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#466]
I think there is a case when there are packages `package1` and `package2` with bundles which share the same **bundle image**. I think two following pieces of code (they work together) might allow upgrading from `package1` to `package2`.

https://github.com/operator-framework/operator-controller/blob/7161a7b62ec17dc36790455b03773a5f14e7671f/internal/resolution/variablesources/bundle_deployment.go#L43-L53

https://github.com/operator-framework/operator-controller/blob/7161a7b62ec17dc36790455b03773a5f14e7671f/internal/resolution/variablesources/installed_package.go#L31-L43

E.g. when catalogs (single catalog or two different catalogs) have something like this:

`package1` bundles:
* `image:tag1` - version `1.0.0`

`package2` bundles:
* `image:tag1` - version `1.0.0`
* `image:tag2` - version `1.0.1`

In this case, _I think_, when we install `package1` at version `1.0.0` and then upgrade - our [installed bundle](https://github.com/operator-framework/operator-controller/blob/7161a7b62ec17dc36790455b03773a5f14e7671f/internal/resolution/variablesources/installed_package.go#L43) might end up being the one from `package2` since we search bundes by image references. And installed bundle is driving successors.

I looked into how to mitigate this in https://github.com/operator-framework/operator-controller/pull/442 but it didn't feel like the right solutiion.

**Comment by joelanford** [comment]
> In this case, I think, when we install package1 at version 1.0.0 and then upgrade - our [installed bundle](https://github.com/operator-framework/operator-controller/blob/7161a7b62ec17dc36790455b03773a5f14e7671f/internal/resolution/variablesources/installed_package.go#L43) might end up being the one from package2 since we search bundes by image references. And installed bundle is driving successors.

This should not be possible if we are filtering bundles by package name based on `Operator.spec.packageName`.

**Comment by m1kola** [comment]
> This should not be possible if we are filtering bundles by package name based on `Operator.spec.packageName`.

We don't seem to do that: I can only see filtering by bundle image [here](https://github.com/operator-framework/operator-controller/blob/a5baf62e55f3dbb7f1cefd7c9e1609db7490e388/internal/resolution/variablesources/installed_package.go#L34). And we filter successors by package name, but we rely on installed package name.

I think as part of work for #449 I will have to have both `Operator` and `BundleDeployment` available in the relevant code (so we can switch between enforcing and ignoring upgrade edge constraints). And it will enable us filtering by package name specified on the `Operator` spec.

**Comment by joelanford** [comment]
Yeah, I think I started to put the pieces together as I reviewed #460, and I left a few comments in this area: 
- https://github.com/operator-framework/operator-controller/pull/460#discussion_r1376252897
- https://github.com/operator-framework/operator-controller/pull/460#discussion_r1376262167
