### ISSUE TITLE
Improve failure messages in operator-developer-e2e condition comparison

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#483]
As shown in #481 today if there is a failure in `operator-developer-e2e` due to unexpected condition we get a message like this:

```
Status conditions for the operator plain-operator for the version 0.2.0 is not as expected:Expected status: True, but got: False
```

We should include condition message when failing test due to unexpected condition as it usually contains useful information.

Relevant code:
https://github.com/operator-framework/operator-controller/blob/a00a93ffb00c3a9fe894c1974e17400933bffebd/test/operator-framework-e2e/operator_framework_test.go#L769-L783

**Comment by trgeiger** [comment]
Since it looks like the tests have been majorly refactored since this was written, is this issue still necessary?

**Comment by m1kola** [comment]
Good call! I think we can close it.
