### ISSUE TITLE
(Placeholder): When `ForceSemverUpgradeConstraints=false` prefer deprecated bundles less during install/upgrade

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#527]
>[!NOTE]
>This issue is a placeholder issue and is subject to change

As part of implementing [RFC: OLMv1 Graph Deprecation](https://docs.google.com/document/d/1CYGANKILfzfOoWtHvyg4luF7i-cC1NRa7_1N9xTLatw/edit?usp=sharing) deprecated bundles should be preferred less than non-deprecated bundles during resolution for installation and upgrading.

The preference will follow the pattern [non-deprecated, ordered by highest → lowest version] [deprecated, ordered by highest → lowest version]

As an example, consider the following scenario:
```
v1.0.0 <-- Deprecated
v1.1.0 <-- Installed
v1.2.0 <-- Long-Term Support
v1.3.0 <-- Deprecated
v1.4.0 <-- Deprecated
v1.5.0 <-- Long-Term Support
```
The resulting list of successors, ordered by most preferred first, would be:
```
v1.5.0
v1.2.0
v1.4.0 <-- Deprecated
v1.3.0 <-- Deprecated
```

**Comment by joelanford** [comment]
While I'm thinking about it (no need to respond)...

Why would we care what state the `ForceSemverUpgradeConstraints` feature flag is in when it comes to deprioritizing deprecated bundles?
