### ISSUE TITLE
Update kapp-controller to allow the use of the `--preflight` flag when using `kapp` as the deployment method

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#688]
Once a version of [carvel-dev/kapp](https://github.com/carvel-dev/kapp) with support for preflight checks has been released _and_ [carvel-dev/kapp-controller](https://github.com/carvel-dev/kapp-controller) has been updated to use that version, kapp-controller needs to be updated to support configuring the preflight checks provided to `kapp` via the `App` CR.

For some additional context as to how `kapp-controller` configures the flags that can be passed to `kapp` via the `App` CR, see https://github.com/carvel-dev/kapp-controller/issues/1381#issuecomment-1957478793

**Comment by joelanford** [comment]
What does this entail? Is it just a bump of the `kapp-controller` version we depend on? Do we know which version of kapp-controller we'll need yet?

**Comment by everettraven** [comment]
>What does this entail? Is it just a bump of the kapp-controller version we depend on? Do we know which version of kapp-controller we'll need yet? 

Sorry, was updating the parent epic issue with some more stuff that we will need to do on the carvel side of things. I made the issue based on a new check box I added so it defaulted to no description. I'm planning to spend some time today to go through all the issues in the parent epic and making sure that all the descriptions are up to date.

**Comment by everettraven** [comment]
Closing this issue as we are no longer planning to build on top of the carvel tool suite
