### ISSUE TITLE
Introduce the spec.Package field to the Operator API

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#69]
- [ ] Introduce the spec.Package field.
- [ ] Create a GA Milestone issue that captures that the spec.Package field will likely need to be changed in order to support other sourcing techniques. For example, installing a bundle image directly
- [ ] Update #62 to include a link to the GA Milestone Issue

**Comment by joelanford** [comment]
Looks like Tim was ahead of us on the GA Milestone issue: https://github.com/operator-framework/operator-controller/issues/60

**Comment by dmesser** [comment]
Will this have any implications on later asks to add a `desiredVersion` to the `spec` block ?

**Comment by awgreene** [comment]
>Will this have any implications on later asks to add a desiredVersion to the spec block ?

We've created [an issue](https://github.com/operator-framework/operator-controller/issues/60) to track the need to install from things other than catalogs (for example, installing the operator from a bundle image url). This will likely lead to a design where that supports multiple types of source declarations, one of which will meet the needs to specify packageName + version.

**Comment by joelanford** [comment]
Closed by #80
