### ISSUE TITLE
Convert Operator CR into Deppy Constraints

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#70]
**User Story:**

As a user, I would like the packageName I specify in the Operator Controller to be converted into a Deppy Constraint.

**Background:**

- The goal of this story is to convert an Operator CR into Deppy Constraints.
- Today, we only plan to introduce the packageName and GVK constraints, but will expand in the future.
- Within the context of Deppy, Variables are logical statements that can be true or false. [Constraints](https://github.com/operator-framework/deppy/blob/main/pkg/ext/olm/constraints.go#L35) are variables that must be true in a solution set. So for this story:
-- The user will specify a package that they want to install within an Operator CR's spec.PackageName field
-- The operator controller will create a "Deppy Variable" that captures this packageName constraint.
-- The Deppy Library will introduce the GVK Uniqueness requirement.

**Acceptance Criteria:**

- An Operator CR can be converted into a set of Deppy Constraints.

**Comment by perdasilva** [comment]
https://github.com/operator-framework/operator-controller/pull/105 closes this issue
