### ISSUE TITLE
Add a check for handling updates to existing fields to decrease the minimums

### ISSUE THREAD

**Issue by rashmigottipati** [operator-framework/operator-controller#713]
This builds on top of [#666](https://github.com/operator-framework/operator-controller/issues/666) and focuses on adding a valid check to ensure that minimums can be decreased for existing fields in a CustomResourceDefinition schema.

If the [proposal](https://github.com/carvel-dev/carvel/pull/729/files) for adding this functionality to [carvel-dev/kapp](https://github.com/carvel-dev/kapp) has been accepted prior to starting this work, all changes should be made against  [carvel-dev/kapp](https://github.com/carvel-dev/kapp), otherwise the changes should be made against https://github.com/everettraven/kapp/tree/feature/crd-upgrade-safety-preflight

**Comment by everettraven** [comment]
The proposal has merged and work is now being tracked in carvel-dev/kapp. This issue is now a tracker for https://github.com/carvel-dev/kapp/issues/913

**Comment by everettraven** [comment]
Closing as https://github.com/carvel-dev/kapp/issues/913 has been closed via a merged PR.
