### ISSUE TITLE
Add a check for ensuring that existing required fields can be marked as optional

### ISSUE THREAD

**Issue by rashmigottipati** [operator-framework/operator-controller#715]
This builds on top of [#666](https://github.com/operator-framework/operator-controller/issues/666) and focuses on adding a valid check to ensure that existing required fields can be marked as optional in a CustomResourceDefinition schema.

If the [proposal](https://github.com/carvel-dev/carvel/pull/729/files) for adding this functionality to [carvel-dev/kapp](https://github.com/carvel-dev/kapp) has been accepted prior to starting this work, all changes should be made against [carvel-dev/kapp](https://github.com/carvel-dev/kapp), otherwise the changes should be made against https://github.com/everettraven/kapp/tree/feature/crd-upgrade-safety-preflight

**Comment by everettraven** [comment]
Proposal merged and work is now being tracked in carvel-dev/kapp. This is now a tracker for https://github.com/carvel-dev/kapp/issues/915

**Comment by rashmigottipati** [comment]
Created a PR (in code review) for this in kapp: https://github.com/carvel-dev/kapp/pull/933

**Comment by rashmigottipati** [comment]
Closing as PR merged in kapp upstream: https://github.com/carvel-dev/kapp/pull/933
