### ISSUE TITLE
Create an interface to Deppy that encapsulates the necessary solver methods

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#72]
**User Story:**
- As a developer on the Operator Controller project, I would like to place any calls to Deppy solver behind a reasonable interface so I can easily test or swap out the Deppy implementation.

**Background:**
- The Deppy project is being developed as a library that third party projects may utilize.
- There is a possibility that the Operator Controller will need to introduce an Kubernetes Native API (a CRD) that will allow users to configure constraints sent to the resolver.
- To support the possible change, calls to the Deppy Solver should be be done through an interface.
- Placing the Solver behind an interface will simplify unit testing as well.
- The existing solver interface can be found [here](https://github.com/operator-framework/deppy/blob/6b4cdde525e61aee9508d5034a8965bc806b96e6/pkg/solver/solver.go#L27-L29).

**Acceptance Criteria:**
- The Deppy Solver is implemented using an interface

**Comment by perdasilva** [comment]
https://github.com/operator-framework/operator-controller/blob/main/internal/resolution/resolver.go is nearly there. I think we should just refactor to remove the entitySource parameter and create that internally in the resolver.
