### ISSUE TITLE
[epic] ClusterExtension Controller embeds helm for managing installed content

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#733]
[Brief](https://docs.google.com/document/d/1GvmHQxjwCOS6xEZqWTCf5UoQB3DzdSMKIKfJZLiG3X0/edit?usp=sharing)

Tasks
- [x] #610 
- [x] #893
- [x] #996

**Comment by varshaprasad96** [comment]
Brief up for review: https://docs.google.com/document/d/1GvmHQxjwCOS6xEZqWTCf5UoQB3DzdSMKIKfJZLiG3X0/edit#heading=h.btd8kkom5km4

**Comment by itroyano** [comment]
Hi,

The engine for applying a helm chart already exists in the helm-operator-plugin code,  so the two main feats here in my opinion are:

1.  Define a structure for a bundle file that represents a Helm chart and values for its installation.
The values part is key.  it needs to have good & clear UX,  and the option for the bundle to provide a validation schema and/or webhooks, such that invalid input will be rejected before running the actual engine.

2. Convert the bundle to something the existing helm engine understands.  a temporary CR that goes into the Unstructured parser code for example, or some other impl.
