### ISSUE TITLE
[epic] ClusterExtension supports simple registry+v1 bundles only

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#734]
### Components
- [x] [Brief](https://docs.google.com/document/d/1Bwhv00KtFfB5JQ_11JAN00YnyehzGPIyYb3mdnc9GxM/edit?usp=drive_link)
- [x] #779
- [x] #815
- [x] #816

**Comment by m1kola** [comment]
This is currently blocked by #846: to meet the requirement about supported install modes we need to bump rukpak so we can benefit from [this fix](https://github.com/operator-framework/rukpak/pull/892). We can not bump rukpak while work on helm integration is still ongoing.

**Comment by m1kola** [comment]
Closing this epic: all relevant issues are done.
