### ISSUE TITLE
[epic] Remove Extension API and controllers from main branch (until after v1 release)

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#735]
The intent is to remove this API and its controllers for the v1.0.0 release. Once we've released 1.0.0, we plan to re-introduce the Extension API and controllers.

**Comment by everettraven** [comment]
@joelanford This epic is marked as "Needs Docs". Is this still the case or can this be closed out?

**Comment by joelanford** [comment]
Not sure! We just need to comb through docs and make sure we don't have anything in there about the old Extension API.

**Comment by everettraven** [comment]
I don't see anything about the old Extension API in the docs. Closing this issue and moving the epic to "Done". Thanks!
