### ISSUE TITLE
Add configuration to the `ClusterExtension` API for disabling CRD Upgrade Safety validations

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#745]
A new, optional, field should be introduced to the `ClusterExtension` API spec for enabling/disabling the CRD Upgrade Safety preflight checks. The default state should be enabled.

**Comment by rashmigottipati** [comment]
PR created in rukpak: https://github.com/operator-framework/rukpak/pull/902

**Comment by rashmigottipati** [comment]
https://github.com/operator-framework/rukpak/pull/902 merged. This added the CRD upgrade safety preflight configuration API into rukpak.

Work to transplant this logic into operator controller is currently blocked by https://github.com/operator-framework/operator-controller/pull/846 and will be tracked by https://github.com/operator-framework/operator-controller/issues/877
