### ISSUE TITLE
[epic] Port relevant Extension reconciler logic over to ClusterExtension

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#747]
We have been working a lot on fine tuning the logic of the Extension controller recently. The major themes have been:
- Make the updates of various status fields more orthogonal
   - resolution results
   - prorgressing state
   - status of the currently installed bundle
   - deprecation status of the currently installed bundle and the specified package and channel
- Removal of deppy due to the lack of a need for a SAT solver.
- Make room in the ClusterExtension API for other techniques for sourcing bundles (i.e. enable a future where bundles don't have to be sourced from a catalog)

Once we wrap that work up, let's port the relevant bits over to the ClusterExtension controller.

**Comment by m1kola** [comment]
Deppy removal PR: https://github.com/operator-framework/operator-controller/pull/758

**Comment by gallettilance** [comment]
Extension API fields in ClusterExtension API #842

**Comment by ankitathomas** [comment]
https://github.com/operator-framework/operator-controller/pull/846 includes the status field updates

**Comment by ankitathomas** [comment]
Closing this out, follow-up work for sourcing bundles from non-catalog sources tracked in https://github.com/operator-framework/operator-controller/issues/906:  [epic #903](https://github.com/operator-framework/operator-controller/issues/903)
