### ISSUE TITLE
Add a check for ensuring that default values are not changed

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#797]
This issue focuses on adding another field change validation to the CRD Upgrade Safety checks to prevent changes to a fields default value for a given CRD version during an upgrade

**Comment by rashmigottipati** [comment]
created a PR for this in kapp upstream: https://github.com/carvel-dev/kapp/pull/950

**Comment by rashmigottipati** [comment]
Closing as completed via PR merged into kapp: https://github.com/carvel-dev/kapp/pull/950
