### ISSUE TITLE
Change makefile to install and verify tools versions in a less fragile way

### ISSUE THREAD

**Issue by dtfranz** [operator-framework/operator-controller#85]
See Joe's comment here for explanation and potential ways we can do this: https://github.com/operator-framework/operator-controller/pull/81#discussion_r1062007819

Rukpak uses a separate tools module in the repo to pull down the go tools binaries for use with the makefile targets. We could do something similar since it's a better implementation than what comes from the generated project here.

Example Makefile: https://github.com/operator-framework/rukpak/blob/main/Makefile
Example tools folder: https://github.com/operator-framework/rukpak/tree/main/hack/tools

**Comment by ankitathomas** [comment]
Solved with https://github.com/operator-framework/operator-controller/pull/252
