### ISSUE TITLE
[Helm integration] Follow up to #846 - change unpacking to direct image registry client approach

### ISSUE THREAD

**Issue by bentito** [operator-framework/operator-controller#853]
PR #846 allows operator-controller to use helm under the hood for package installs. It is using a separate binary, `unpack`, to manage image unpacking. This issue proposes to use a direct image registry client approach to save the need to create a separate binary. The work would be very similar to that done on rukpak here: https://github.com/operator-framework/rukpak/pull/874

**Comment by tmshort** [comment]
Is this basically done?

**Comment by bentito** [comment]
I think it is actually done.

**Comment by tmshort** [comment]
Was there a PR? #905?
