### ISSUE TITLE
[epic] Implement upgrade tests for OperatorController

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#856]
In order to have confidence that feature additions and bug fixes are reflected after an upgrade, we should add a suite of upgrade tests that:
1. Install the most recent public release.
2. Create objects that sufficiently exercise our API surface and behaviors.
3. Upgrade in place from the most recent public release to a build from the current commit.
4. Make assertions that prove that changes from the current commit are reflected.

**Comment by acmenezes** [comment]
Hi @joelanford , I'm sorry I didn't have much progress on this task on the previous week. I'm quite busy with some partner work here. I'll just drop an /unassign here to open space for others to work on this. As soon as I have a few extra cycles I'll be back.
