### ISSUE TITLE
[Helm Integration] Evaluate if we need to store unpacked bundles in cache.

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/operator-controller#869]
Operator controller currently implements the store interface from Rukpak, using a localdir, to so store unpacked contents. 
Evaluate if this is required after changing the unpack to use directly registry client.

**Comment by tmshort** [comment]
Is this done?

**Comment by joelanford** [comment]
This is not done.  I'm pretty sure we store the unpacked bundles twice. Once in an unpacker cache and once in the `Storage` implementation.

**Comment by joelanford** [comment]
This was fixed by #1050 .
