### ISSUE TITLE
Improve unit testing of `reconcile()` function.

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#879]
As discussed in the meeting earlier today, I'd like to see us move to a model where this functions is a bit easier to unit test by creating logical abstractions where they make sense and mocking them during unit testing.

Totally fine with this being a follow-up, just commenting to track the recommendation :)

_Originally posted by @everettraven in https://github.com/operator-framework/operator-controller/pull/846#discussion_r1604028873_

**Comment by joelanford** [comment]
This was closed by #1068 and #1033
