### ISSUE TITLE
Review Reason and Type strings in ClusterExtension API.

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#880]
We discussed a similar topic [here](https://github.com/operator-framework/operator-controller/pull/846/#discussion_r1601374857): do we really need these reasons? I don't think we have a use case for this just yet.

`ReasonErrorGettingClient` can be replaced with a more generic `ReasonInstallationFailed`. Same, probably, goes for `ReasonBundleLoadFailed` too, but there is another question about related condition type `TypeHasValidBundle` above.

See also #842

_Originally posted by @m1kola in https://github.com/operator-framework/operator-controller/pull/846#discussion_r1604761276_

**Comment by tmshort** [comment]
@bentito are you basically working on this?

**Comment by bentito** [comment]
yes

**Comment by tmshort** [comment]
We did a whole API review. So closing this old issue.
