### ISSUE TITLE
Limit the number of unpack retries

### ISSUE THREAD

**Issue by tmshort** [operator-framework/operator-controller#882]
Clarification: Is this a statement or something that needs to be done in the future?
 
```             
// There must be a limit to number of entries if status is stuck at
// unpack pending.
```

_Originally posted by @everettraven in https://github.com/operator-framework/operator-controller/pull/846#discussion_r1607078005_

**Comment by joelanford** [comment]
No I don't think we should have a limit. Let exponential back off do its thing.

**Comment by tmshort** [comment]
So we should close this?

**Comment by everettraven** [comment]
IIRC this was from a PR comment I made about a code comment. I'm fine with closing this, but maybe we should make sure we clean that comment up as well if it is not applicable.
