### ISSUE TITLE
Evaluate the use of conditions and reasoning in cluster extension controller

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/operator-controller#893]
https://github.com/operator-framework/operator-controller/pull/874#discussion_r1617678266

**Comment by bentito** [comment]
I'm looking at this now. @varshaprasad96 what's a good work output for this one? A document with the Conditions and Reasons explained along with their setting logic summarized with links to usage in the current code base? Should I create a Jira to track this issue?

**Comment by varshaprasad96** [comment]
@bentito yes, that would be a good start. We can start with a RFC that explains what each of the conditions are and what they intend to do. That'd be helpful in evaluating the use of all 7 conditions, and check if we can minimize them. I can create a JIRA to track and help with this.

**Comment by tmshort** [comment]
Closing as RFC has been completed.
