### ISSUE TITLE
catalogmetadata client adds extreme latency to reconciliation

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#914]
I've narrowed this latency down to the `Bundles()` call that is made for every single reconcile.

I added logging to the `catalogmetadata.Client.Bundles()` call to report start time and end time, and the function consistently takes around 30s, and it pegs a CPU.

This seems like a bug we should treat with a fairly high priority.

**Comment by bentito** [comment]
I added some timing data to the Bundles func too, documenting times for the various return points (https://gist.github.com/bentito/9fbf0d81354caa52121f5c4e294bd506).  The fake catalog is just 1 entry I think? Would ~350µs (the longest test timing in 1 run (not scientific!) * number items in real catalog * # of calls to Bundle get close to 30s?

**Comment by joelanford** [comment]
I think that's probably an order of magnitude off still. I suspect that our fake catalog entry isn't as complex and varied as what exists in operatorhub in terms of what takes the most time (i.e. icons, olm.bundle.object properties).

**Comment by acornett21** [comment]
Are we talking about [this](https://github.com/operator-framework/operator-controller/blob/main/internal/catalogmetadata/client/client.go#L46) function? Or something else?

**Comment by joelanford** [comment]
Yep, that's the one.
