### ISSUE TITLE
Bug: Bundle image source should use ext.Spec.InstallNamespace, not systemNamespace

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#944]
See: https://github.com/operator-framework/operator-controller/blob/f301f552978ed4997a09e04fbfccc586237461ee/cmd/manager/main.go#L180

This likely means a slight refactoring of the ImageRegistry implementation.

Related: it probably makes sense to stop using the composite unpacker and instead just use `ImageRegistry` directly.

**Comment by m1kola** [comment]
`ImageRegistry` is now being used, but it looks like we still need to fix `AuthNamespace`: 

https://github.com/operator-framework/operator-controller/blob/cf8b866d86bc6e30b3606a8e13dd4ffd6c2b74f0/cmd/manager/main.go#L197-L202

**Comment by m1kola** [comment]
This namespace is [only used](https://github.com/operator-framework/operator-controller/blob/ec1640bf1f0e772ff02fe080b7c6fe18fbf0f734/internal/rukpak/source/image_registry.go#L79) when there is [image pull secret specified](https://github.com/operator-framework/operator-controller/blob/ec1640bf1f0e772ff02fe080b7c6fe18fbf0f734/internal/rukpak/source/image_registry.go#L76) and we currently [do not specify it](https://github.com/operator-framework/operator-controller/blob/ec1640bf1f0e772ff02fe080b7c6fe18fbf0f734/internal/controllers/clusterextension_controller.go#L239-L244). So as far as I understand - this does not affect anything _at the moment_. @joelanford or am I missing something?

If we set `AuthNamespace` to  `ext.Spec.InstallNamespace` this will mean that we will have to create a pull secret for image registry in the `ext.Spec.InstallNamespace`. Is this what we want to achieve? Oh, and we will also have to have a pull secret support (has to be in line with #1015, I suspect).
