### ISSUE TITLE
The catalogd and operator-controller metrics services target each other

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#955]
The label selector used for both catalogd and operator-controller metrics services is: `control-plane: controller-manager`. Now that both catalogd and operator controller are running in the same namespace, that means both services target both pods.

This will lead to a confusing prometheus metrics collection. We need to do a sweep of labels and label selectors used in catalogd and operator controller to make sure we do not actually overlap.

**Comment by LalatenduMohanty** [comment]
PR #969 sent to fix in this repo.

**Comment by LalatenduMohanty** [comment]
PR for catalogd https://github.com/operator-framework/catalogd/pull/292

**Comment by LalatenduMohanty** [comment]
https://github.com/operator-framework/operator-controller/pull/969 has merged.
