### ISSUE TITLE
[epic] v1.0.0 Documentation

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#959]
Documentation is necessary in order to properly release a project, announce it to the world, and drive adoption. Good documentation is also very helpful for users and maintainers to understand design intent, which can sometimes help explain to users why they see certain behaviors or to maintainers, provide context around questions in code.

As part of a v1.0 release, we need to have documentation that covers the following:

- [x] #1305
- [x] #1122
- [x] #1123
- Reference
  - [x] #1124
  - [x] #1125 (should be done after Catalogd API review epic is completed)
  - [x] #1126 (should be done after the Operator-Controller API review epic is completed)
  - [x] #984
  - [x] #1132 
- Howto
  - [x] #1127
  - [x] #1128
  - [x] #1129
  - [x] #1130
  - [x] #1217
  - [x] #1229

Current documentation is posted up at https://operator-framework.github.io/operator-controller/
New docs should be placed in [docs/drafts](https://github.com/operator-framework/operator-controller/tree/main/docs/drafts)

**Comment by m1kola** [comment]
I just created #984 about OLMv1 limitations which we might want to include into this epic as well.

**Comment by LalatenduMohanty** [comment]
Closing this epic as all tasks are marked done.
