### ISSUE TITLE
[epic] Improve kustomize layouts across OLMv1 components

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#967]
Recently we've done some work related to TLS support that has uncovered some difficulty in navigating the existing layout of manifests and utilization of kustomize to compose the V1 components and install them as a "single entity". Some of the struggles we've encountered are:
- Difficulty in sharing CAs for TLS certificates across namespaces
- Shared namespaces (switched to this pattern to resolve ^) causes some clashing related to labels and selectors, especially for metrics
- Separate component repositories and installation steps results in potentially clashing resources (i.e shared namespace, cert-manager resources, etc.)

To mitigate this, it was discussed offline between a few of the maintainers and determined that it would be worth the effort to re-think our manifest layouts and how we compose the OLMv1 components for installation. The goal of this epic is to capture the need for this work and serve as an area of discussion / planning. 

- [x] #1000
- [x] https://github.com/operator-framework/catalogd/issues/295

**Comment by tmshort** [comment]
As part of this, the consolidation of the ClusterIsser and dependencies need to be consoilidated. Currently, it is being applied via a HEREDOC for the e2e's and a separate YAML file for Tide.

Getting these resources into the kustomize config will fix this issue.

**Comment by tmshort** [comment]
RFC: https://docs.google.com/document/d/1w1IGgE5M40jFIrSuY74E8PnSQn_ihWnjdoFedl6lp8c/edit?usp=sharing

**Comment by tmshort** [comment]
See: https://github.com/operator-framework/operator-controller/pull/970

**Comment by tmshort** [comment]
This is basically done.
