### ISSUE TITLE
[Bug] Reconciliation of cluster extension content not working on main branch

### ISSUE THREAD

**Issue by skattoju** [operator-framework/operator-controller#983]
Since we setup watches for all objects installed by a cluster extension. It is expected that the controller will reconcile cluster extension content in case any of it is modified. However this does not work as expected. 

Steps to reproduce:
1. Switch to main branch
2. `make run` 
3.  Deploy sample catalog
4. Deploy sample extension
5. Delete deployment of extension controller

Expected Result:
The controller should react and recreate the deployment

Actual Result:
The controller does not react

**Comment by bentito** [comment]
Hi, thanks for the bug report. So to check things out, I immediately ran `make test-e2e`. All pass and we think they're fairly realistic end-to-end tests, so... Any chance you could reframe this bug report more along the lines of these tests (or at least with similar components and usages, Kind cluster, the catalog installer script, etc)? Seems like it would be more likely to result in a reproducer and be something folks can work on.

**Comment by skattoju** [comment]
Hi Brett, there is not yet an e2e test for this scenario, I guess it will get implemented as part of work related to #737 The way the content is watched is changing so this will probably be fixed when #975 is done.

**Comment by joelanford** [comment]
This test would be independent of the SA work. We should specifically track it to make sure the functionality works as expected.
