### ISSUE TITLE
Docs: OLM v1 limitations

### ISSUE THREAD

**Issue by m1kola** [operator-framework/operator-controller#984]
There are a number of limitations in OLMv1 which we would like to document.

The first category of limitations is what described in [this brief](https://docs.google.com/document/d/1Bwhv00KtFfB5JQ_11JAN00YnyehzGPIyYb3mdnc9GxM/edit). When a user installs an extension we perform bundle validation we are able to check for these limitations and indicate an issue in `ClusterExtension`'s conditions

* We only support bundles which support [install mode](https://olm.operatorframework.io/docs/advanced-tasks/operator-scoping-with-operatorgroups/#targetnamespaces-and-their-relationship-to-installmodes) `AllNamespaces`.
* We do not currently support bundles with webhooks.
* We do not support bundles with dependencies declared as any of the following: olm.gvk.required, olm.package.required and olm.constraint). See [this doc](https://olm.operatorframework.io/docs/reference/file-based-catalogs/) for more info on these FBC properties.

We also have the following limitations which is not possible to validate at the install time. Issues from this category of limitations will not be obvious from `ClusterExtension`'s conditions since we are unable to catch them at install time based on metadata.

* We do not support `OperatorConditions` API. We do not plan to support this API "as is" in OLMv1, but we are considering ([issue](https://github.com/operator-framework/operator-controller/issues/739)) adding an alternative OLMv1 API (not in 1.0.0). Most of the operators who rely on this API will fail on startup, but some might fail during reconciliation (depends on operator implementation).

**Comment by michaelryanpeter** [comment]
/assign

- Also create a snippet admonition that can be reused in other parts of the docs.
